### ISSUE TITLE
PointPillars to ONNX

### ISSUE THREAD

**Issue by hz3014** [muzi2045/second_TANET.pytorch#1]
Hey, I was wondering how did you export your pytorch modle to onnx? Did you use SmallMunich code to export it to pfe.onnx and rpn.onnx or did you export the whole modle into one onnx file?

**Comment by muzi2045** [comment]
the best way to export pointpillars to onnx is split it into two part.
because the pillars scatter have to be writen in CUDA kernel, or you can write the scatter layer into trt plugin.
I'm not using other onnx export scripts, because here is some place in network I changed for more faster inference speed, so I write it myself.

**Comment by hz3014** [comment]
> eca

I have been working on exporting Second(NuScenes) to onnx for weeks and I am very confused. It seems like everything in voxelnet.py need to be modified. Would you please show some guidelines for exporting onnx?
